### ISSUE TITLE
Bug in cycle_load()?

### ISSUE THREAD

**Issue by ulrichfilippi** [open-ideas/StROBe#16]
In cycle_load(), for a FridgeFreezer, calculated power is currently standby (zero for FridgeFreezer) except for single minutes where it is cycle_power (190 for FridgeFreezer). In other words, P is [0, ..., 0, 190, 0, ..., 0, 190, 0, ...]. Therefore, cycle_power is kept only for one minute, independent of cycle_length. Is this a bug or did I misinterpret?

**Comment by Mathadon** [comment]
@rubenbaetens @cprotopa  do you have some wisdom to share about this?

**Comment by cprotopa** [comment]
Indeed, there is a problem with the implementation, the power is only kept for the 1st minute of the cycle. I'll need to take a closer look to propose a fix to this model. Thanks for pointing it out!
