### ISSUE TITLE
Produce temperature setpoints in K

### ISSUE THREAD

**Issue by cprotopa** [open-ideas/StROBe#27]
In IDEAS, all temperatures are expressed in SI units, thus Kelvin. The implementation there also requires that the inputs for TSet be in K, as expressed in [https://github.com/open-ideas/IDEAS/pull/1127](https://github.com/open-ideas/IDEAS/pull/1127).  Therefore I will propose to create a boolean parameter in StROBe that chooses to output TSet in C or K. The default would then be in K. 
Anybody disagrees with this? @bramvdh91 @SilkeVerbruggen ?

**Comment by SilkeVerbruggen** [comment]
I don't see any problem with that.
