### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by xavfa** [open-ideas/StROBe#36]
It might be a silly question but...do you plan to make it compatible with Python3 ?

**Comment by cprotopa** [comment]
Hello @xavfa. It would indeed be useful. However, this project is managed  on a voluntary basis, so somebody has to volunteer their time to do that, and that's not currently planned. If you are interested, you can, of course contribute!

**Comment by nlsmth** [comment]
I took a shot at this here [https://github.com/nlsmth/StROBe/tree/python3](StROBe). It works for the example, but probably needs some further testing.

**Comment by xavfa** [comment]
Hi thank you very much for this, I began with same changes when I've noticed this new branch. Unfortunately, i am blocked it a ModuleNotFoundError: No module named 'numpy.core.multiarray\r' error....while load the irradiance file (pickle issue). Quite well known issue on the web but none of the solution works for me...I am in windows10, python 3.7 and virtualenv... I will continue to dig into but if you have any idea of a workaround i'd be grateful.

**Comment by cprotopa** [comment]
@nlsmth, thank you very much for this contribution! I've reviewed your code, and also run a small test on my PC and it seems to work fine, unless there is a change in the way some functions work, which I'm not aware of. I think you could make a pull request. 

@xavfa, I didn't get any such error. Did you use the same adaptations as @nlsmth ? (see here: https://github.com/open-ideas/StROBe/compare/master...nlsmth:python3) 

I suppose everyone would be fine switching to Python 3, but maybe I'll make a branch with the Python 2 version, in case somebody still needs it.

**Comment by nlsmth** [comment]
@xavfa upgrade numpy to the latest version.

**Comment by xavfa** [comment]
Thanks again for your reply, for the changes yes, I used the full python3 branche from git. For numpy, yes but there is a bug with last numpy version and windows (https://developercommunity.visualstudio.com/content/problem/1207405/fmod-after-an-update-to-windows-2004-is-causing-a.html). using the previous one does not resolve the issue. To my understanding it rely on the way irradiance.txt has been compiled for the python2 version and the \r versus \n but i can't find a workaround even following several proposals. (https://stackoverflow.com/questions/58194852/modulenotfounderror-no-module-named-numpy-core-multiarray-r)...

**Comment by cprotopa** [comment]
@xavfa @nlsmth Perhaps we can change this irradiance file to be a simple text file instead of a pickled file? 
I'm not sure there is any advantage in using a pickle file here.

**Comment by nlsmth** [comment]
Removing pickle would work as a hammer solution I think. There is changes
in how pickle decodes files in python3. @xavfa I would try changing the
encoding here:

[residential.py](
https://github.com/nlsmth/StROBe/blob/python3/Corpus/residential.py#L416)

**Comment by xavfa** [comment]
well, thanks for the tip.
I've tired so many different ways... the link sent before were also applied where you point at (l416). 
I even tried this morning the following proposal https://rebeccabilbro.github.io/convert-py2-pickles-to-py3/, but same error occur...I even read some 32bit\64bit related issue or nkf conversions....too much for my skills
Maybe @cprotopa you could put another irradiance file in the git in order to make a try: except: in the code.... if possible.
Anyway, thank you both for your concerns.

**Comment by xavfa** [comment]
by the way, I am on windows10 pro, python 3.7, and dedicated virtualenv. what OS do you have ?

**Comment by Mathadon** [comment]
Not sure whether I understood the problem correctly: Is it simply a matter of replacing the line endings in a txt file?

**Comment by xavfa** [comment]
I don't understand fure sure neither :)... the first try : replace('\r\n','\n') don't work, same issue, this is why I beginning to have doubts on the OS

**Comment by Mathadon** [comment]
Does anyone know what type of data is in there? Perhaps it's better to convert it to a csv orso using python2 and use the csv from now on. But a csv is likely larger, and the file is already a few MB..

https://raw.githubusercontent.com/open-ideas/StROBe/master/Data/Climate/irradiance.txt

**Comment by Mathadon** [comment]
Or convert it into csv using python2, then pickle the csv using python3..

**Comment by cprotopa** [comment]
The text file is actually smaller (2.1MB): [irradiance.txt](https://github.com/open-ideas/StROBe/files/5493245/irradiance.txt)
@xavfa, if you use `irr = np.loadtxt('Climate/irradiance.txt')` in `residential`, it should work, right? 
@nlsmth, if you can make a pull request with your changes for Python3, could you add this change as well? Or I can add it afterwards.

**Comment by xavfa** [comment]
In the meantime I have installed python 2.7.9 and it work great (I struggled a lot with previous version of python...https://help.dreamhost.com/hc/en-us/articles/115000221112-Using-pip-to-install-Python-2-modules#:~:text=SNIMissingWarning%3A%20An%20HTTPS%20request%20has,Python%20version%20older%20than%202.7.&text=If%20you%20need%20to%20install,it's%20newer%20than%20version%202.7.).
using your file @cprotopa works also well in python 3 ! There is still a deprecation warning in numpy, but not damageable. 
Please, if I go fiurther with this package, what shall be the reference ? do you have a publication I can cite ?

**Comment by xavfa** [comment]
I cached the ref in the front page. sorry. I guess we can close this issue ?

**Comment by cprotopa** [comment]
@xavfa, glad it works now. 
Indeed, the [references ](https://github.com/open-ideas/StROBe#references) are at the bottom of the readme file. 
I'd keep the issue open until the Python 3 implementation is integrated in the repository. A pull request is necessary for that.

**Comment by nlsmth** [comment]
@cprotopa the loadtxt function is giving me some errors. I will submit a PR and come back to it.
