### ISSUE TITLE
Temperature setpoints

### ISSUE THREAD

**Issue by celiamstrnk** [open-ideas/StROBe#40]
Hello, 

I have a question about the temperature sepoints. Indeed, I noticed differences between the temperature of the different sepoints given in the article _Modelling uncertainty in district energy simulations by stochastic residential occupant behaviour_, and those of the code. 
In the paper, the following table is given for the heating patterns: 
![image](https://user-images.githubusercontent.com/85284460/154114988-185cdc5c-baca-49ad-a315-2fcdac1a8bc4.png)
In StrROBe/Corpus/residential.py (line 518 to 523), there are the following values: 
![image](https://user-images.githubusercontent.com/85284460/154115192-ce8af87c-dedd-44ab-b154-5012270c5e53.png).

I wonder if there is reversal between the state sleeping and absent. For example, for the setting type "3", I obtain the following setpoints and occupancy: 

![825e4b7f-ac0c-42e7-b890-411000eadce7](https://user-images.githubusercontent.com/85284460/154115747-1efe12b5-1329-4f67-bcb7-baedf122d339.jpg)
![c8b9f16f-9114-4535-800d-12017c121808](https://user-images.githubusercontent.com/85284460/154115732-01cd8443-8084-4f88-ae84-0593f6aa7048.jpg)

When the occupants are sleeping, we have Tset = 15°C, whereas according to table 2, we should have 19.5°C. Is that normal? 

Thank you very much ! 

Best regards, 

Célia Masternak (PhD Student at the GeePs laboratory, under the supervision of Vincent Reinbold, Simon Meunier, Dirk Saelens and Claude Marchand)

**Comment by Mathadon** [comment]
@jelgerjansen can you comment on this by any chance?

**Comment by cprotopa** [comment]
Very well spotted. I'm pretty sure it's a typo in the paper though. If you look at the referenced source Leidelmeijer & Van Grieken (2005) (in Dutch though), they clearly say that people typically have an average high setpoint in the day, higher in the evening (when active), and much lower during the night. This translates to a low set-point when sleeping, a high set-point when active, and a possibly equaly high set-point when away (assuming still during the day). This is also mentioned inside the paper in the explanation of the heating: "a typical space heating profile heating the day-zone just below 20°C all day long, increasing their set-point in the evening while reducing it at night to 15°C." 
So I think the code is correct, at least concerning this part! :)

**Comment by celiamstrnk** [comment]
Ok, it makes sense ! Thank you very much for your answer !

**Comment by Mathadon** [comment]
@celiamstrnk thanks for reporting and @cprotopa thanks for resolving the issue!
