### ISSUE TITLE
Parameter calibration after fix in #4

### ISSUE THREAD

**Issue by cprotopa** [open-ideas/StROBe#9]
Pull request #4 has fixed certain problems, but re-calibration of parameters is needed to achieve same annual averages.

**Comment by bramvdh91** [comment]
What is the status of this issue?

**Comment by cprotopa** [comment]
I had looked into this and made some "calibration", but couldn't really achieve real conversion. I'll have to check again, cause it's been a year since that.

**Comment by cprotopa** [comment]
This has no sense anymore, many changes have been made since. Therefore I close this issue.
